# -*- coding: utf-8 -*-
"""decoder_LLM

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/#fileId=https%3A//storage.googleapis.com/kaggle-colab-exported-notebooks/adrinbienvenidopavn/decoder-llm.b5aaa161-0b68-4f79-9a54-e323a4dfb641.ipynb%3FX-Goog-Algorithm%3DGOOG4-RSA-SHA256%26X-Goog-Credential%3Dgcp-kaggle-com%2540kaggle-161607.iam.gserviceaccount.com/20260425/auto/storage/goog4_request%26X-Goog-Date%3D20260425T164350Z%26X-Goog-Expires%3D259200%26X-Goog-SignedHeaders%3Dhost%26X-Goog-Signature%3D0624ebf222610903d3f9f3d21ddb3a2c21ef83d38b0cb27e27b84b6af1f32820e3386d852d0ec848b5b0a8aff4dd955ef2d87081c738e26e8e23afc8bec6fd9dec0b0911fde9070e889b8360c423a45eafa18c346d2b2c589ed81243067535b2259de0fb2fc3f4b8efe1d2209114ff91cc3b9bb880d58a6be206aa5aeb80caf343f7456d5a1365a23b970de1d6a794eac46ed95941c7c6411d7505362e04d3dfbc5ac97de925146abc1e8260392e5fe71e71a66fb55c581d09577e2179e91b5a517443061e8f8c3466df08e52d506d1e24d3ac4ff471f7ff8da88cb82fe96317d807ae11db5ea70ea5326f0036acb4e30f3dfb0ad4996fd5d4d4f4d9995c1ba7
"""

mjgut05_dataset_marketing_path = kagglehub.dataset_download('mjgut05/dataset-marketing')

print('Data source import complete.')

import os
import json
import torch
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from torch.utils.data import Dataset, DataLoader
from transformers import (
    GPT2Tokenizer,
    GPT2LMHeadModel,
    get_linear_schedule_with_warmup,
)
from torch.cuda.amp import autocast, GradScaler

# =============================================================================
# CONFIGURACION
# =============================================================================
CONFIG = {
    "ruta_dataset": "/kaggle/input/datasets/mjgut05/dataset-marketing/dataset_marketing.parquet",

    "nombre_modelo": "gpt2",
    "longitud_maxima": 256,

    "epocas": 4,
    "tamano_lote": 4,
    "tasa_aprendizaje": 5e-5,
    "pasos_calentamiento": 100,
    "pasos_acumulacion_gradiente": 2,
    "decaimiento_peso": 0.01,

    "proporcion_entrenamiento": 0.70,
    "proporcion_validacion": 0.15,
    "proporcion_test": 0.15,

    "directorio_salida": "./outputs/gpt2_marketing_completo",
    "guardar_cada_n_epocas": 1,

    "semilla": 42,
}

SEMILLA = CONFIG["semilla"]
torch.manual_seed(SEMILLA)
np.random.seed(SEMILLA)

# =============================================================================
# FUNCIONES DE PROCESAMIENTO
# =============================================================================
def construir_par_entrenamiento(fila):
    """Construye par (entrada, salida) para el modelo de lenguaje"""
    caracteristicas = fila["features"] if isinstance(fila["features"], list) else []
    detalles = fila["details"] if isinstance(fila["details"], dict) else {}

    if caracteristicas:
        ficha = " | ".join(caracteristicas)
    elif detalles:
        ficha = " | ".join(f"{k}={v}" for k, v in detalles.items())
    else:
        ficha = fila["title"]

    texto_entrada = ficha
    texto_salida = fila["description_clean"]

    return texto_entrada, texto_salida

def obtener_prompt(texto_entrada, texto_salida):
    """Formato de prompt estructurado para Causal LM"""
    return f"Input: {texto_entrada}\nOutput: {texto_salida}"

class DatasetProductos(Dataset):
    """Dataset optimizado con Carga Perezosa (Lazy Loading)"""

    def __init__(self, df, tokenizador, longitud_maxima):
        self.df = df.reset_index(drop=True)
        self.tokenizador = tokenizador
        self.longitud_maxima = longitud_maxima

    def __len__(self):
        return len(self.df)

    def __getitem__(self, indice):
        fila = self.df.iloc[indice]

        texto_entrada, texto_salida = construir_par_entrenamiento(fila)
        prompt_completo = obtener_prompt(texto_entrada, texto_salida)

        codificacion = self.tokenizador(
            prompt_completo,
            truncation=True,
            max_length=self.longitud_maxima,
            padding="max_length",
            return_tensors="pt",
        )

        ids_entrada = codificacion["input_ids"].squeeze()
        mascara_atencion = codificacion["attention_mask"].squeeze()

        etiquetas = ids_entrada.clone()
        etiquetas[mascara_atencion == 0] = -100

        return {
            "input_ids": ids_entrada,
            "attention_mask": mascara_atencion,
            "labels": etiquetas,
        }

# =============================================================================
# FUNCION PRINCIPAL DE ENTRENAMIENTO
# =============================================================================
def ejecutar_entrenamiento():
    dispositivo = torch.device("cuda" if torch.cuda.is_available() else "cpu")

    print("\n" + "=" * 60)
    print(" INICIO PIPELINE: GPT-2 CON NOMENCLATURA EN ESPAÑOL")
    print(f" Dispositivo: {dispositivo} | Epocas: {CONFIG['epocas']}")
    print("=" * 60 + "\n")

    # -- CARGA DE DATOS --
    print(" Cargando dataset completo...")
    df = pd.read_parquet(CONFIG["ruta_dataset"])
    print(f" Registros totales en origen: {len(df):,}")

    columnas_requeridas = ["features", "details", "title", "description_clean"]
    df = df[columnas_requeridas].copy()

    # Estratificacion por longitud de texto
    df["_len_bin"] = pd.cut(
        df["description_clean"].str.len(),
        bins=5,
        labels=False
    ).fillna(0).astype(int)

    print(" Realizando division de datos estratificada...")
    df_entreno, df_temporal = train_test_split(
        df,
        test_size=CONFIG["proporcion_validacion"] + CONFIG["proporcion_test"],
        stratify=df["_len_bin"],
        random_state=SEMILLA,
    )

    df_val, df_test = train_test_split(
        df_temporal,
        test_size=0.5,
        stratify=df_temporal["_len_bin"],
        random_state=SEMILLA,
    )

    del df, df_temporal
    import gc
    gc.collect()

    print(f" Entrenamiento: {len(df_entreno):,} | Val: {len(df_val):,} | Test: {len(df_test):,}")

    # -- PREPARACION DEL MODELO --
    print("\n Cargando arquitectura del modelo...")
    tokenizador = GPT2Tokenizer.from_pretrained(CONFIG["nombre_modelo"])
    tokenizador.pad_token = tokenizador.eos_token

    modelo = GPT2LMHeadModel.from_pretrained(CONFIG["nombre_modelo"])
    modelo.resize_token_embeddings(len(tokenizador))
    modelo.to(dispositivo)

    # -- CONFIGURACION DE DATALOADERS --
    ds_entreno = DatasetProductos(df_entreno, tokenizador, CONFIG["longitud_maxima"])
    ds_val = DatasetProductos(df_val, tokenizador, CONFIG["longitud_maxima"])
    ds_test = DatasetProductos(df_test, tokenizador, CONFIG["longitud_maxima"])

    cargador_entreno = DataLoader(ds_entreno, batch_size=CONFIG["tamano_lote"], shuffle=True)
    cargador_val = DataLoader(ds_val, batch_size=CONFIG["tamano_lote"], shuffle=False)
    cargador_test = DataLoader(ds_test, batch_size=CONFIG["tamano_lote"], shuffle=False)

    # -- OPTIMIZADOR Y PLANIFICADOR --
    optimizador = torch.optim.AdamW(
        modelo.parameters(),
        lr=CONFIG["tasa_aprendizaje"],
        weight_decay=CONFIG["decaimiento_peso"],
    )

    pasos_totales = len(cargador_entreno) * CONFIG["epocas"] // CONFIG["pasos_acumulacion_gradiente"]

    planificador = get_linear_schedule_with_warmup(
        optimizador,
        num_warmup_steps=CONFIG["pasos_calentamiento"],
        num_training_steps=pasos_totales,
    )

    escalador = GradScaler() if dispositivo.type == "cuda" else None

    # -- BUCLE DE ENTRENAMIENTO --
    historial = {"perdida_entreno": [], "perdida_val": []}
    os.makedirs(CONFIG["directorio_salida"], exist_ok=True)

    print(" Iniciando iteraciones de aprendizaje...")

    for epoca in range(1, CONFIG["epocas"] + 1):
        modelo.train()
        perdida_total_entreno = 0
        optimizador.zero_grad()

        for paso, lote in enumerate(cargador_entreno):
            ids_entrada = lote["input_ids"].to(dispositivo)
            mascara_atencion = lote["attention_mask"].to(dispositivo)
            etiquetas = lote["labels"].to(dispositivo)

            if escalador:
                with autocast():
                    salidas = modelo(input_ids=ids_entrada, attention_mask=mascara_atencion, labels=etiquetas)
                    perdida = salidas.loss / CONFIG["pasos_acumulacion_gradiente"]
                escalador.scale(perdida).backward()
            else:
                salidas = modelo(input_ids=ids_entrada, attention_mask=mascara_atencion, labels=etiquetas)
                perdida = salidas.loss / CONFIG["pasos_acumulacion_gradiente"]
                perdida.backward()

            perdida_total_entreno += perdida.item() * CONFIG["pasos_acumulacion_gradiente"]

            if (paso + 1) % CONFIG["pasos_acumulacion_gradiente"] == 0:
                if escalador:
                    escalador.unscale_(optimizador)

                torch.nn.utils.clip_grad_norm_(modelo.parameters(), 1.0)

                if escalador:
                    escalador.step(optimizador)
                    escalador.update()
                else:
                    optimizador.step()

                planificador.step()
                optimizador.zero_grad()

        perdida_media_entreno = perdida_total_entreno / len(cargador_entreno)

        # Validacion
        modelo.eval()
        perdida_total_val = 0
        with torch.no_grad():
            for lote in cargador_val:
                ids_entrada = lote["input_ids"].to(dispositivo)
                mascara_atencion = lote["attention_mask"].to(dispositivo)
                etiquetas = lote["labels"].to(dispositivo)
                salidas = modelo(input_ids=ids_entrada, attention_mask=mascara_atencion, labels=etiquetas)
                perdida_total_val += salidas.loss.item()

        perdida_media_val = perdida_total_val / len(cargador_val)
        historial["perdida_entreno"].append(perdida_media_entreno)
        historial["perdida_val"].append(perdida_media_val)

        print(f" Epoca {epoca}/{CONFIG['epocas']} | Perdida Entreno: {perdida_media_entreno:.4f} | Perdida Val: {perdida_media_val:.4f}")

        # Guardar estado actual
        ruta_estado = os.path.join(CONFIG["directorio_salida"], f"checkpoint_epoca_{epoca}")
        modelo.save_pretrained(ruta_estado)
        tokenizador.save_pretrained(ruta_estado)

    # -- EVALUACION FINAL --
    print("\n" + "=" * 60)
    print(" EVALUACION FINAL SOBRE CONJUNTO DE TEST")
    print("=" * 60)

    modelo.eval()
    perdida_total_test = 0
    with torch.no_grad():
        for lote in cargador_test:
            ids_entrada = lote["input_ids"].to(dispositivo)
            mascara_atencion = lote["attention_mask"].to(dispositivo)
            etiquetas = lote["labels"].to(dispositivo)
            salidas = modelo(input_ids=ids_entrada, attention_mask=mascara_atencion, labels=etiquetas)
            perdida_total_test += salidas.loss.item()

    print(f" Perdida final en Test: {perdida_total_test / len(cargador_test):.4f}")

    with open(os.path.join(CONFIG["directorio_salida"], "historial_completo.json"), "w") as f:
        json.dump(historial, f, indent=2)

    print(f"\n Pipeline finalizado con exito. Archivos en: {CONFIG['directorio_salida']}")

if __name__ == "__main__":
    ejecutar_entrenamiento()